improve openapi validation
pagopa/interop-be-catalog-management pull request #175
Opened 2022-09-02 16:14 UTC by beetlecrunch

2022-09-02 16:34 UTC, galales requested changes

2022-09-02 16:34 UTC, galales commented on src/main/scala/it/pagopa/interop/catalogmanagement/api/impl/package.scala
> +  def problemOf(
most of this function calls use a single error parameter.
I missed where more than one error is passed, but If it is required I suggest to overload `problemOf` to be able to keep the old signature

2022-09-02 17:12 UTC, beetlecrunch commented on src/main/scala/it/pagopa/interop/catalogmanagement/api/impl/package.scala
> +  def problemOf(
It's Friday ... I haven't thought about this simple solution.

Thank you!

2022-09-05 12:57 UTC, galales approved these changes

2022-09-05 13:58 UTC, TonioGela approved these changes
LGTM. Isn't this a good moment to maybe move `Problem` and its serde into commons?

2022-09-05 14:15 UTC, beetlecrunch commented
> LGTM. Isn't this a good moment to maybe move `Problem` and its serde into commons?

Is it possible? `Problem` depends on code generation and I think is not possible to exclude it from generation.

2022-09-06 09:31 UTC, TonioGela commented
> > LGTM. Isn't this a good moment to maybe move `Problem` and its serde into commons?
> 
> Is it possible? `Problem` depends on code generation, and I think is not possible to exclude it from generation.

AFAIK it's just a matter of not using it, in the sense that we can change the import in the templates. TECHNICALLY we won't use the definition we are exposing in the open API spec, but since it's a thing that changes just once a decade, the boilerplate reduction will be worth it. IMHO.

2022-09-06 15:30 UTC, merged