Adding URL to EService
pagopa/interop-be-catalog-management pull request #211
Opened 2022-12-21 12:13 UTC by bloodsky

Errors inside PersistentSerializationSpec: serde/deserde checks must be moved in commons?

2022-12-21 13:03 UTC, galales commented on models/src/main/scala/it/pagopa/interop/catalogmanagement/model/CatalogDocument.scala
> +  serverUrls: List[String]
any reason why the new field is both in the descriptor and in the document?
IMO it could be just in the descriptor, because the document is generic and could be any file, but I'm not aware of considerations done for this ticket

2022-12-21 14:43 UTC, beetlecrunch commented on models/src/main/scala/it/pagopa/interop/catalogmanagement/model/CatalogDocument.scala
> +  serverUrls: List[String]
I agree with @galales

2022-12-21 17:08 UTC, galales requested changes

2022-12-21 17:08 UTC, galales commented on src/main/scala/it/pagopa/interop/catalogmanagement/model/persistence/projection/EServiceCqrsProjection.scala
> -      if (isInterface)
you can remove brackets here and [here](https://github.com/pagopa/interop-be-catalog-management/pull/211/files?diff=split&w=1#diff-47a816ca70013b7d46ccce1ded9ea424047598057d62b9796b9120bf27023b79R66)

2022-12-21 17:08 UTC, galales commented on src/main/scala/it/pagopa/interop/catalogmanagement/model/persistence/projection/EServiceCqrsProjection.scala
> +    case CatalogItemDocumentDeleted(esId, dId, docId)                      =>
`serviceUrls` in the descriptor needs to be emptied if the document is the interface

2022-12-22 10:33 UTC, beetlecrunch approved these changes

2022-12-22 11:05 UTC, TonioGela approved these changes
LGTM, just address what Alessio said

2022-12-22 11:14 UTC, galales approved these changes

2022-12-22 11:17 UTC, merged